name: science
channels:
  - defaults
  - conda-forge
  - cogsci
dependencies:
  - python=3.4
  - numpy
  - ipython
  - matplotlib
  - scipy
  - pytest
  - pytest-cov
  - coverage
  - pip
  - opencv
  - pygame
  - pip:
    # - -r requirements.txt
    # - pygame

