name: science
channels:
  - defaults
  - conda-forge
  - cogsci
dependencies:
  - python
  - numpy
  - ipython
  - matplotlib
  - pytest
  - pip
  - pygame
  - pip:
    # - -r requirements.txt
    # - pygame

