name: science
channels:
  - defaults
  - conda-forge
  - cogsci
dependencies:
  - python=3.9
  - numpy
  - ipython
  - matplotlib
  - pytest
  - pip
  - typing_extensions
  - pip:
    # - -r requirements.txt
    - pygame
    - ipdb
    - pandas

